export enum Actions{
  APPLICATION_HTTP_MESSAGE = "APPLICATION_HTTP_MESSAGE",
  REMOVE_APPLICATION_MESSAGE = "REMOVE_APPLICATION_MESSAGE",
  SET_USER_INFO = "SET_USER_INFO",
  LOADING_USERS = "LOADING_USERS",
  LOADED_USERS = "LOADED_USERS",
  LOADING_COMMIT_TRANSACTION = "LOADING_COMMIT_TRANSACTION",
  UPDATE_BALANCE = "UPDATE_BALANCE",
  PUSH_TRANSACTION = "PUSH_TRANSACTION",
  SET_TRANSACTIONS = "SET_TRANSACTIONS"
}